search without specs
hunter298/qna pull request #19
Opened 2020-09-13 20:25 UTC by hunter298

Реализована функция поиска по вопросам, ответам, комментариям и пользователям. 
Есть возможность совершить общий поиск, сразу по всем возможным объектам, а также возможность поиска отдельно по вопросам/ответам/комментариям/пользователям.

2020-09-14 08:55 UTC, IvanShamatov requested changes
Пока первые правки.

2020-09-14 08:55 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +    rescue ActiveRecord::RecordNotFound => e
Это общая ошибка в системе, и реакция на нее общая. Если запись не найдена, то вне зависимости от экшена нужно делать rescue

```ruby
class ApplicationController < ActionController::Base
  rescue_from ActiveRecord::RecordNotFound, :with => :record_not_found

  def record_not_found
    render json: {error: 'Record not found'}, status: :not_found
  end
end
```

2020-09-14 08:55 UTC, IvanShamatov commented on app/controllers/api/v1/answers_controller.rb
> +          render json: {error: @error}, status: 204
204 это некорректный статус для этого сообщения, потому что контент есть, и ты его отдаешь json'ом

2020-09-14 08:55 UTC, IvanShamatov commented on app/controllers/api/v1/questions_controller.rb
> +    begin
еще одна обработка, которой стоило бы избежать

2020-09-14 08:55 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    question.comments.destroy_all
если у модели комментариев есть depend destroy, то отдельно вызывать удаление комментариев не нужно.
https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-dependent

2020-09-14 08:55 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    question.comments.destroy_all
хмм, ты таки сделал, а строчку оставил, что-то не сработало?

2020-09-14 08:55 UTC, IvanShamatov commented on app/indices/users_index.rb
> +  has admin, created_at, updated_at
зачем нам в результатах поиска, является ли пользователь админом или нет?

2020-09-14 08:55 UTC, IvanShamatov commented on app/models/application_record.rb
> +  SEARCH_CLASSES = %w[Question Answer Comment User].freeze
не думаю, что это лучшее место для этого. По факту оно нужно в SearchController, и используется в соотвесттвующей вьюхе

2020-09-14 10:00 UTC, hunter298 commented on app/controllers/questions_controller.rb
> +    question.comments.destroy_all
там же полиморфная связ, dependent не работает, это с юзером обычная зависимость

2020-09-14 10:43 UTC, IvanShamatov commented on app/controllers/questions_controller.rb
> +    question.comments.destroy_all
а блин, сорян, ты прав

2020-09-14 10:44 UTC, IvanShamatov commented on app/controllers/searches_controller.rb
> +    query_class = params[:query_class]
Тут следует проверять, входит ли твой квери-класс в список допустимых.

2020-09-14 13:25 UTC, vkurennov commented on config/development.sphinx.conf
> +
вот это и конфиг для test надо удалить из репо и добавить в .gitignore и туда же всю директорию db/sphinx

2020-09-14 13:26 UTC, vkurennov commented on app/controllers/searches_controller.rb
> +  def search
а где тесты контроллера на это?

2020-09-15 09:55 UTC, IvanShamatov requested changes
еще комментов тебе

2020-09-15 09:55 UTC, IvanShamatov commented on app/views/searches/_result.html.slim
> +  p = link_to result.title, "/questions/#{result.id}"
Если у тебя результат вполне определенный ActiveRecord инстанс, то и пути ты можешь строить с помощью роут хелперов
`= link_to result.title, result`

2020-09-15 09:55 UTC, IvanShamatov commented on app/views/searches/_result.html.slim
> +  p = link_to result.title, "/questions/#{result.id}"
Если же это не эктив-рекорд, то как минимум можно воспользоваться роут хелпером уровня
`= link_to result.title, question_path(result.id)`

2020-09-15 09:55 UTC, IvanShamatov commented on app/views/searches/_result.html.slim
> +  p = link_to  result.body.truncate(40), "/questions/#{Answer.find(result.commentable_id).question.id}/\#answer-#{Answer.find(result.commentable_id).id}"
очень плохо, что ты делаешь поиски во вьюшках, 
У тебя тут получается 2x(N+1) запроса к базе данных на каждой странице поиска. А сам подумай, такой сервис только так и работает -- через поиск. Это значит что каждый твой пользователь будет супер-нагружать твой сервис каждым своим поисковым запросом и отрисовкой этой странице.

Это как раз тот случай, когда для реализации удобной юзерской истории стоит придумать нетуториаловское решение:
Например, нам нужно сделать линк для коммента, который зависит от типа. Но нам абсолютно не обязательно делать это в цикле для абсолютно каждого результата. Потому что не все эти ссылки нам нужны.
```ruby
- elsif result.is_a?(Comment)
  p = link_to  result.body.truncate(40), comment_path(result)
```

Что если мы соорудим такой контроллер для комментов, который будет в зависимости от своего типа редиректить на разные страницы?

2020-09-15 09:55 UTC, IvanShamatov commented on spec/features/question/answer_subscription_spec.rb
> +        sleep 1
sleep - это путь вникуду. нужно либо page.reload использовать, или еще раз делать visit этой страницы

2020-09-15 12:57 UTC, IvanShamatov commented on app/views/searches/_result.html.slim
>    p = link_to  result.body.truncate(40), "/questions/#{result.commentable_id}"
а вот это забыл?

2020-09-15 13:00 UTC, IvanShamatov commented on app/models/answer.rb
> +  def path
это не является логикой модели, это какой-то хелпер для отрисовки урла.

2020-09-15 13:03 UTC, IvanShamatov commented on app/views/searches/_result.html.slim
> +  p = link_to result.body.truncate(40), "/questions/#{result.question_id}/\#answer-#{result.id}"
и вот эту штуку уже тоже можно упростить, имея хелпер с path

2020-09-15 21:05 UTC, merged